### ISSUE TITLE
Common setup event phase error

### ISSUE THREAD

**Issue by Lordbaane** [Markus1002/Autumnity#11]
This issue comes up once in a while along with Quark, Buzzier Bees, and Berry Good.
https://pastebin.com/H3zJwT6H

**Comment by Lordbaane** [comment]
Quark/Vazkii believes the issue lies here

**Comment by Markus1002** [comment]
That's a problem with Forge and it happens with other mods too. There isn't anything I can do about it.

**Comment by Pannoniae** [comment]
Any idea what the problem is? Or should I open an issue at Forge? (My modpack crashes like half the time with the same or similar error message)

**Comment by Pannoniae** [comment]
They say it's not their issue.

**Comment by pau101** [comment]
This is all of these listed mod's faults. You cannot register material compostability during a parallel event, as `CompostorBlock` is not thread safe.

**Comment by Pannoniae** [comment]
Thank you very much @pau101!

**Comment by Pannoniae** [comment]
I see this won't get fixed. How sad.
