### ISSUE TITLE
Odd Spawning?

### ISSUE THREAD

**Issue by SilverKytten** [Markus1002/Autumnity#15]
I'm sure this is from mod conflicts, but I figured I'd report it anyway because I got a good chuckle out of it. Running Autumnity-1.3.0-1.15.2 w/Forge-31.1.63
![2020-05-17_15 43 23](https://user-images.githubusercontent.com/2188185/82159983-b71e1480-9857-11ea-9db2-b6c3311537d1.png)

Here's a list of mods I'm running, I have a feeling it's conflict with Botania and/or Buzzier Bees, if it's not something you can fix.
[Modlist.zip](https://github.com/Markus1002/Autumnity/files/4641022/Modlist.zip)

**Comment by Markus1002** [comment]
Looks like a graphical glitch. I have no idea what could be causing it. It's probably a conflict with some mod that affects rendering. Its definitely not a conflict with Buzzier Bees, in fact this mod and Buzzier Bees has some cross-content.

**Comment by SilverKytten** [comment]
It’s not graphical, it’s definitely stuff spawned into the world. 

Sorry I didn’t reply last night, I figured out what was causing it but had such a headache from trying to work with twitch launcher all day that as soon as I fixed the issue I went to bed. 

https://www.curseforge.com/minecraft/mc-mods/economy-inc
Is the culprit, though I’m not entirely sure why. 🤷🏼‍♀️😂

**Comment by Markus1002** [comment]
I'm glad that you got it fixed.
