### ISSUE TITLE
[Suggestion] More Textures for Pumpkin Faces

### ISSUE THREAD

**Issue by SpiderKolo** [Markus1002/Autumnity#16]
Since this mod is strongly about Autumn and things related to it, it could be nice to have more types of Lanterns made from Pumpkins.

I propose pumpkins to be cut in a cyclic manner, where you have X faces + the vanilla face + No face (default).
In order to access new faces, you have to keep using Scissors on already cut Pumpkin.
From 0 (no face) to 1 (vanilla face),
then from 1 to 2 (new faces start from there),
from 2 to 3, from 3 to 4...
from X back to 1 and from there cycle repeats.

Optionally, you could add Recipes for Corail's Woodcutter where you can apply and change face of the pumpkin without wasting your scissors.

Each of those pumpkins could be turned into Jack o'Lantern and/or used to summon a Snowman with that cut of Pumpkin.

If Snowman is not your pair of shoes, how about Scarecrow? Who also have unique faces?
New Golem-like creature you summon using Fences and Wheat. Or just Fences. Or just Wheat...
(Optionally there could be a Support for Quark and Bamboo Blocks which adds Thatch blocks perfect for filling!)

That mob could be completely stationary, but would scare away all passive mobs (except Villagers who can tell it's not dangerous) in desant range, as well as speed-up growth of crops slightly.

But be careful! He is not the best for defense and will anger other aggressive creatures who will mistake him for a player!

Wait... that might be also useful for some traps...

**Comment by Markus1002** [comment]
I've been planning on adding scarecrows for a short while now and they might be coming in the future. There is already a mod that adds new pumpkin faces: https://www.curseforge.com/minecraft/mc-mods/oh-my-gourd

**Comment by SpiderKolo** [comment]
Oh, that's cool! This is EXACLY what I was asking for and I was not aware of this!
If you add the Scarecrow... would you consider adding support for that other mod then? So Scarecrow would use new pumpkin faces.
