### ISSUE TITLE
Missing recipe for maple chest

### ISSUE THREAD

**Issue by DesertDweller** [Markus1002/Autumnity#23]
I get the following error on load:
Couldn't parse loot table autumnity:blocks/maple_chest
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'autumnity:maple_chest'

I looked in the jar file (v 1.3.1) and could not find the recipe.

**Comment by Markus1002** [comment]
Maple chests are added by Quark when both mods are installed. The error will be fixed in the next update.
