### ISSUE TITLE
Add compatibility for Corail's Woodcutter

### ISSUE THREAD

**Issue by Insane96** [Markus1002/Autumnity#6]
So we can use planks into the woodcutter

**Comment by Markus1002** [comment]
You should ask the creator of Corail Woodcutter instead.

**Comment by Insane96** [comment]
I've asked him and:
![image](https://user-images.githubusercontent.com/7185104/80300827-2f853e80-87a0-11ea-8991-66535d625cc5.png)

**Comment by Markus1002** [comment]
Well I might do that if I have time.

**Comment by Insane96** [comment]
Or #9
