### ISSUE TITLE
[1.15.2]Fluid Pipes Dont connect to rftools Builder Machine

### ISSUE THREAD

**Issue by Morpheus1101** [Markus1002/Autumnity#8]
Forge: 31.1.9
Autumnity: 1.2.0

None of the Fluid Pipes will connect to the rftools builder machine, which is a valid block for pumping out fluids.

**Comment by Bobisnotap** [comment]
Autumnity doesn't add fluid pipes

**Comment by Morpheus1101** [comment]
This is a good example of not doing stuff late at night lol
